;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="GameplayCue.VFX.Player.AOEImpact",NewTagName="GameplayCue.VFX.AOEImpact.Thunder")
+GameplayTagRedirects=(OldTagName="GameplayCue.SVFX.Actor.Hero.Buff.DamageResist",NewTagName="GameplayCue.SVFX.Actor.Hero.Buff.SubSkill.DamageResist")
+GameplayTagRedirects=(OldTagName="GameplayCue.SVFX.Actor.Hero.Buff.MaxHealth",NewTagName="GameplayCue.SVFX.Actor.Hero.Buff.SubSkill.MaxHealth")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Cooldown.Attack",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SVFX.Actor.Hero",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SVFX.Actor.Hero.Buff",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SVFX.Actor.Hero.Buff.SubSkill.AttackPower",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SVFX.Actor.Hero.Buff.SubSkill.DamageResist",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SVFX.Actor.Hero.Buff.SubSkill.MaxHealth",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SVFX.Actor.Hero.Buff.VolumeUp",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SVFX.Actor.Hero.HitImpact",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SVFX.Actor.Unit.Buff.AttackPower",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SVFX.Actor.Unit.Debuff.AttackPower",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SVFX.Shared.BuffLooping",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SVFX.Shared.DebuffLooping",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SVFX.Shared.HealCast",DevComment="즉시 발동하는 힐을 받은 대상에게 적용할 큐")
+GameplayTagList=(Tag="GameplayCue.SVFX.Shared.HealLooping",DevComment="지속적인 힐의 큐")
+GameplayTagList=(Tag="GameplayCue.SVFX.Shared.HitImpact",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SVFX.Static.Hero.Buff.Cost",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SVFX.Static.Hero.HitImpact",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SVFX.Static.Hero.HitImpact.Blunt",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SVFX.Static.Hero.HitImpact.Sword",DevComment="")
+GameplayTagList=(Tag="GameplayCue.VFX.Unit.HitImpact",DevComment="")
+GameplayTagList=(Tag="UI.CoolTime",DevComment="UI 테스트용 태그")

