;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Attack.Skill",DevComment="")
+GameplayTagList=(Tag="Ability.Cooldown.Attack",DevComment="")
+GameplayTagList=(Tag="GameplayCue.VFX.Player.AOEImpact",DevComment="")
+GameplayTagList=(Tag="GameplayCue.VFX.Player.TestHit",DevComment="")
+GameplayTagList=(Tag="GameplayCue.VFX.Unit.HitImpact",DevComment="")
+GameplayTagList=(Tag="UI.CoolTime",DevComment="UI 테스트용 태그")

