// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

//
// 태그를 정의하는 곳
//
namespace PGGameplayTags
{
    // 인풋 태그
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_BasicAttack);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_ActiveSkill);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_ActiveSkill_SubSkill);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_ActiveSkill_MainSkill);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_InputBlock_Move);

    // 플레이어 어빌리티 태그
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Combat_BasicAttack);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Combat_Skill);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Combat_Skill_SubSkill);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Combat_Skill_MainSkill);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Die);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Initialize);

    // 어빌리티 태그
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Cooldown_MainSkill);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Cooldown_SubSkill);

    // 플레이어 세트 게임 플레이 태그 
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Equipment_Set_ChainSword);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Equipment_Set_Ironmaid);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Equipment_Set_Justice);

    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Equipment_Set_Dimension);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Equipment_Set_Healer);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Equipment_Set_FireballMaster);

    // 이벤트 트리거
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Trigger_OnHit);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Trigger_OnKill);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Trigger_OnCommit);

    // 어트리뷰트 태그
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Health);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_MaxHealth);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Cost);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_AttackPower);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_MoveSpeed);

    // 스탯 관련 SetByCaller 태그
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_SetByCaller_MaxHealth);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_SetByCaller_AttackPower);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_SetByCaller_MoveSpeed);

    // 유닛 어빌리티 태그
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Ability_MagicCharge);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Ability_Buff);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Ability_BasicAttack);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Ability_SpecialAttack);

    // 공유 이벤트 태그
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeTraceStart);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeTraceEnd);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_ProjectileSpawn);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_ActorSpawn);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_ActorDestroy);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_AOEExecute);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact); // 히트 리액트 이벤트 태그
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_SupportExecute);

    // 공유 SetByCaller 태그
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_SkillMultiplier);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseAmount);
    UNREAL_PROJECTG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_Duration);

    //유닛 상태(State) 태그
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_State_Idle);
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_State_Combat);
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_State_Move);
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_State_Dead);
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_State_Guard);
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_State_Invincible);

    //유닛 등급 태그
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Tier_Normal);
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Tier_Rare);
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Tier_Epic);

    //유닛 속성 태그
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Element_Fire);
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Element_Water);
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Element_Electric);

    //유닛 병과 태그
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Branch_Melee);
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Branch_Ranged);
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Branch_Mage);
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Branch_Tank);

    //아군 적군 구분 태그
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Side_Ally);
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Side_Foe);

    //유닛 버프 디버프 태그
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_VFX_Unit_Dbuff_Poison); //지속적인 체력 감소
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_VFX_Unit_Dbuff_Slow); //이속감소
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_VFX_Unit_Dbuff_Weekness); //공격력감소
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_VFX_Unit_Dbuff_Frozen); //공속감소

    UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_VFX_Unit_Buff_Boost); // 이속증가
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_VFX_Unit_Buff_berserk); // 공격속도증가
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_VFX_Unit_Buff_Warth); // 공격력증가
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_VFX_Unit_Buff_Clam); // 방어력? 추가체력? 증가
    UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_VFX_Unit_Buff_Divinity); //여러 효과 합친 강력한 버프들

}
